### ISSUE TITLE
Maven / Jcenter ?

### ISSUE THREAD

**Issue by RobbWatershed** [omicronapps/7-Zip-JBinding-4Android#7]
Do you have any plans to publish your library to a central repo such as Maven or Jcenter ?

**Comment by omicronapps** [comment]
AAR library now published on [JFrog Bintray](https://bintray.com/omicronapps/7-Zip-JBinding-4Android/net.sf.sevenzipjbinding/16.02-2.01). Not currently available on JCenter due to package name conflict with the [7-Zip-JBinding](https://github.com/borisbrodski/sevenzipjbinding) JAR library, Updated instructions for importing and declaring library dependency here: [README.md](https://github.com/omicronapps/7-Zip-JBinding-4Android/blob/master/README.md).

**Comment by RobbWatershed** [comment]
Bintray is fine as well. I did as you told in the README, the source were successfuly imported, but none of the .so files. I checked the gradle folder and only found the JARs and the POM, nor the AAR.

Is there something I'm doing wrong ?


PS : Thanks for creating the library, it's well-documented, flexible enough to fit my needs and works like a charm (been using the self-built AAR so far) 💯
